services:
  db:
    image: postgres:15
    platform: linux/arm64/v8
    container_name: botacademy_db
    restart: always
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    platform: linux/amd64
    container_name: metabase
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: botdb
      MB_DB_PORT: 5432
      MB_DB_USER: botuser
      MB_DB_PASS: botpass
      MB_DB_HOST: db

